---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app.malike.kendeh.com
  resources:
  - samplekinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.malike.kendeh.com
  resources:
  - samplekinds/finalizers
  verbs:
  - update
- apiGroups:
  - app.malike.kendeh.com
  resources:
  - samplekinds/status
  verbs:
  - get
  - patch
  - update
