# permissions for end users to view samplekinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samplekind-viewer-role
rules:
- apiGroups:
  - app.malike.kendeh.com
  resources:
  - samplekinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.malike.kendeh.com
  resources:
  - samplekinds/status
  verbs:
  - get
