# permissions for end users to view samplekind.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samplekind-viewer-role
rules:
- apiGroups:
  - app.malike.kendeh.com
  resources:
  - samplekind
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.malike.kendeh.com
  resources:
  - samplekind/status
  verbs:
  - get
