apiVersion: app.malike.kendeh.com/v1alpha1
kind: SampleKind
metadata:
  name: lewis-sample
spec:
  image:
    repository: ghcr.io/malike/mock-operator/sample-mock-service
    tag: latest
    pullPolicy: Always
    pullSecretName:
    - name: regcred
  nodes: 2
  containerPort: 80
  servicePort: 80
